"""
Base types for the Signals module.

Defines the Signal dataclass and SignalDetector protocol that all
signal detectors must implement.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import TYPE_CHECKING, Any, Literal, Protocol

if TYPE_CHECKING:
    from bot.core.candle_aggregator import Candle


class SignalType(Enum):
    """Types of trading signals."""

    MOMENTUM = "MOMENTUM"
    RSI = "RSI"
    MACD = "MACD"
    VOLUME_PROFILE = "VOLUME_PROFILE"


@dataclass
class Signal:
    """
    A trading signal generated by a signal detector.

    Represents a potential trading opportunity with direction,
    strength, and metadata about what triggered it.
    """

    coin: str
    signal_type: SignalType
    direction: Literal["LONG", "SHORT"]
    strength: float  # 0.0-1.0, higher = stronger signal
    timestamp: datetime
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        """Validate signal strength is in valid range."""
        if not 0.0 <= self.strength <= 1.0:
            raise ValueError(f"Signal strength must be 0.0-1.0, got {self.strength}")

    @property
    def is_long(self) -> bool:
        """True if this is a LONG signal."""
        return self.direction == "LONG"

    @property
    def is_short(self) -> bool:
        """True if this is a SHORT signal."""
        return self.direction == "SHORT"

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "coin": self.coin,
            "signal_type": self.signal_type.value,
            "direction": self.direction,
            "strength": self.strength,
            "timestamp": self.timestamp.isoformat(),
            "metadata": self.metadata,
        }


class SignalDetector(Protocol):
    """
    Protocol for signal detectors.

    All signal detectors must implement the detect method that takes
    a coin symbol and list of candles, returning a Signal if detected.
    """

    def detect(self, coin: str, candles: list["Candle"]) -> Signal | None:
        """
        Detect a trading signal from candle data.

        Args:
            coin: The trading pair symbol (e.g., "BTC", "ETH")
            candles: List of candles, most recent last

        Returns:
            Signal if a pattern is detected, None otherwise
        """
        ...
