"""
Base types for the Signals module.

Defines the Signal dataclass and SignalDetector protocol that all
signal detectors must implement.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import TYPE_CHECKING, Any, Literal, Protocol

if TYPE_CHECKING:
    from bot.core.candle_aggregator import Candle


class SignalType(Enum):
    """Types of trading signals."""

    MOMENTUM = "MOMENTUM"
    RSI = "RSI"
    MACD = "MACD"
    VOLUME_PROFILE = "VOLUME_PROFILE"


@dataclass
class Signal:
    """
    A trading signal generated by a signal detector.

    Represents a potential trading opportunity with direction,
    strength, and metadata about what triggered it.

    Position info (entry_price, stop_loss, take_profit) can be set by
    SignalsFactory after signal generation, based on market context.
    """

    coin: str
    signal_type: SignalType
    direction: Literal["LONG", "SHORT"]
    strength: float  # 0.0-1.0, higher = stronger signal
    timestamp: datetime
    metadata: dict[str, Any] = field(default_factory=dict)

    # Position info - populated by SignalsFactory
    entry_price: float | None = None
    stop_loss: float | None = None
    take_profit: float | None = None
    atr: float | None = None  # ATR at signal time, for reference

    def __post_init__(self) -> None:
        """Validate signal strength is in valid range."""
        if not 0.0 <= self.strength <= 1.0:
            raise ValueError(f"Signal strength must be 0.0-1.0, got {self.strength}")

    @property
    def is_long(self) -> bool:
        """True if this is a LONG signal."""
        return self.direction == "LONG"

    @property
    def is_short(self) -> bool:
        """True if this is a SHORT signal."""
        return self.direction == "SHORT"

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "coin": self.coin,
            "signal_type": self.signal_type.value,
            "direction": self.direction,
            "strength": self.strength,
            "timestamp": self.timestamp.isoformat(),
            "metadata": self.metadata,
            "entry_price": self.entry_price,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
            "atr": self.atr,
        }

    @property
    def has_position_info(self) -> bool:
        """True if position info (entry, SL, TP) has been set."""
        return self.entry_price is not None and self.stop_loss is not None

    @property
    def risk_reward_ratio(self) -> float | None:
        """Calculate risk/reward ratio if position info is set."""
        if not self.has_position_info or self.take_profit is None:
            return None
        risk = abs(self.entry_price - self.stop_loss)  # type: ignore
        reward = abs(self.take_profit - self.entry_price)  # type: ignore
        return reward / risk if risk > 0 else None


class SignalDetector(Protocol):
    """
    Protocol for signal detectors.

    All signal detectors must implement the detect method that takes
    a coin symbol and list of candles, returning a Signal if detected.
    """

    def detect(self, coin: str, candles: list["Candle"]) -> Signal | None:
        """
        Detect a trading signal from candle data.

        Args:
            coin: The trading pair symbol (e.g., "BTC", "ETH")
            candles: List of candles, most recent last

        Returns:
            Signal if a pattern is detected, None otherwise
        """
        ...
